### ISSUE TITLE
PyPi Registration Question

### ISSUE THREAD

**Issue by AP6YC** [LuisScoccola/persistable#31]
This issue is non-blocking for my JOSS review.

Sorry if I missed it in the documentation somewhere, but is there a plan to register the package on PyPi and perhaps conda-forge? I noticed that the name `persistable` is already taken on PyPi, which is rather unfortunate. Is this the reason, or is something else keeping PyPi registration? Mind you, I don't consider it a big deal to not register on these servers, but there is perhaps added visibility for your package that the convenience for installation could bring.

**Comment by LuisScoccola** [comment]
Thank you for bringing this up! There is such a plan: the package is currently registered as [persistable-clustering](https://pypi.org/project/persistable-clustering/). This will be added to the readme and documentation with the next release, which will be done in the next week or so.

**Comment by AP6YC** [comment]
Excellent! You are already on top of it. Thank you for answering my question.
