### ISSUE TITLE
Clustering Parameters Question

### ISSUE THREAD

**Issue by AP6YC** [LuisScoccola/persistable#32]
This question is non-blocking for my JOSS review.

Is there a plan to make the parameters stateful or transferrable? For example, after I select some desirable parameters using the `persistable` method, where do the parameters "live," so to speak, and how could I use these parameters to cluster on another dataset after reloading? I do understand that there is a `quick_cluster` method in your API, which I appreciate, but as I understand it this method automatically selects parameters based upon the ranges provided. Sorry again if this is due to my misunderstanding of the tool, which is why I add this issue as non-blocking.

**Comment by LuisScoccola** [comment]
Thank you for pointing this out. The parameters selected with the UI can be accessed by calling `PersistableInteractive`'s method `_chosen_parameters()`. The parameters can then be used as input for `Persistable`'s method `cluster()`. However, right now `_chosen_parameters()`  is an internal method and is not documented. I think it is a good idea to turn it into a user-facing method and to add it to the API. This will be done in the next release.

**Comment by AP6YC** [comment]
That answers my question perfectly, thank you! Looking forward to that addition in the release.
