### ISSUE TITLE
API Index

### ISSUE THREAD

**Issue by AP6YC** [LuisScoccola/persistable#33]
This is a relatively low-level request that I have for the documentation, which I otherwise enjoy, but I would like to see an index of the core types and methods of the package in the API reference section. For example, I wonder if it is possible in the `sphinx` docs setup that you use for the documentation to, in the API section, have a list of types and their methods that link to their full definitions further down the page (in the way that you have currently).

If this is limited by the tools that `sphinx` provides, it is no worries. I just know that other packages such as those for documenting Julia code allow for an index functionality.

**Comment by LuisScoccola** [comment]
Thank you for the suggestion. I think I understand what you are referring to, but, just to be sure, could you please provide an example?

**Comment by AP6YC** [comment]
Sure thing! I am thinking of the following from the Julia `Documenter.jl` package (which is actually itself used for generating documentation for Julia projects, like `sphinx` is frequently used):

https://documenter.juliadocs.org/stable/lib/public/

It may just come in the form of the `toctree` directive (sphinx docs): https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree
Or perhaps an autosummary (sphinx rtd theme docs): https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/api.html#generated-index
Or a module index with links (example): https://documen.tician.de/codepy/py-modindex.html

But I also see that it may be comparing apples to oranges. After more digging, I don't see an obvious way of doing this in the Python ecosystem. I don't want to be to picky, and defer to what you think is best for the project.

**Comment by LuisScoccola** [comment]
Thank you for the clarifications. Here's an attempt: https://persistable.readthedocs.io/en/latest/api.html

**Comment by AP6YC** [comment]
That looks great! I very much apologize for the delay. You have indeed done an excellent job and implemented something better than I imagined. Closing this and my review 👍
