### ISSUE TITLE
Error listing upon suggested tests

### ISSUE THREAD

**Issue by jonesparg** [LuisScoccola/persistable#48]
These errors occurred when I ran the following tests shown on the GitHub page after installing persistable on the command line, which went without problems:

pip install pytest playwright pytest-playwright
python -m playwright install --with-deps
pip install -r requirements.txt
python -m setup build_ext --inplace
pytest .

As suggested, I'm sending them on.  See attached screen grab.  

<img width="652" alt="ErrorListing_28Nov2023" src="https://github.com/LuisScoccola/persistable/assets/22328360/9614dd4a-2351-49b3-ae06-588ab3b62a20">

**Comment by jonesparg** [comment]
It could be some strange anaconda issue.  Wouldn't be the first time.

**Comment by LuisScoccola** [comment]
Hi @jonesparg, thank you for reaching out! Did you run the commands from the root of directory of a clone of the repository?

**Comment by jonesparg** [comment]
I did not clone the repository - at least that I am aware of.  I'm not much
of a GitHub user.  I just installed persistable locally on my computer,
then ran the tests.  Does one have to clone the repository in order to get
everything to work?

Apologies - I do work in Python but am primarily an R programmer, coming
over from the statistics side of things.  R is a bit of a different beast
in terms of installing packages and so forth.

**Comment by LuisScoccola** [comment]
Yes, right now the tests check that persistable can run on your computer (rather than checking if the version installed with pip is running properly). Thus, you need to clone the repository, and then run those commands from the root directory of the repository clone. Let me know if you encounter any issues.

**Comment by jonesparg** [comment]
Right.  First time I've cloned a repository and actually put it on my
computer.  I'll give it a go.
It's never too late for an old statistician to learn new tricks.

**Comment by jonesparg** [comment]
Okay, that wasn't hard.
It all worked and I think I am set to go, even if I use the Anaconda
environment instead of VSCode which is generally more tractable for me.
